all:
  children:
    cmc:
      vars:
        ansible_user: root
        ansible_password: "{{ cmcpassword }}"
      hosts:
        cmc-9-obm.nerc-ocp-prod.rc.fas.harvard.edu:
        cmc-10-obm.nerc-ocp-prod.rc.fas.harvard.edu:
    systems:
      vars:
        ansible_user: core
        ansible_python_interpreter: /usr/bin/python3.9
      children:
        systems_on_cmc9:
          vars:
            cmcaddr: cmc-9-obm.nerc-ocp-prod.rc.fas.harvard.edu
          hosts:
            wrk-72:
              macaddr: 10:7d:1a:9d:f5:81
              bmcaddr: wrk-72-obm.nerc-ocp-prod.rc.fas.harvard.edu
              ansible_host: 10.30.8.82
              cmcslot: server-1a
            wrk-74:
              macaddr: 10:7d:1a:9d:f5:e9
              bmcaddr: wrk-74-obm.nerc-ocp-prod.rc.fas.harvard.edu
              ansible_host: 10.30.8.84
              cmcslot: server-1c
            wrk-75:
              macaddr: 10:7d:1a:9d:fc:27
              bmcaddr: wrk-75-obm.nerc-ocp-prod.rc.fas.harvard.edu
              ansible_host: 10.30.8.85
              cmcslot: server-1d
            wrk-76:
              macaddr: 10:7d:1a:9d:f5:9b
              bmcaddr: wrk-76-obm.nerc-ocp-prod.rc.fas.harvard.edu
              ansible_host: 10.30.8.86
              cmcslot: server-3a
            wrk-77:
              macaddr: 10:7d:1a:9d:f7:dd
              bmcaddr: wrk-77-obm.nerc-ocp-prod.rc.fas.harvard.edu
              ansible_host: 10.30.8.87
              cmcslot: server-3b
            wrk-78:
              macaddr: 10:7d:1a:9d:f6:03
              bmcaddr: wrk-78-obm.nerc-ocp-prod.rc.fas.harvard.edu
              ansible_host: 10.30.8.88
              cmcslot: server-3c
