- hosts: systems
  gather_facts: false
  collections:
    - community.general
  vars:
    redfish_base_url: "https://{{ bmcAddr }}"
    reset_type: GracefulShutdown
  tasks:
    - delegate_to: localhost
      uri:
        url: "{{ redfish_base_url }}/redfish/v1/Systems/System.Embedded.1"
        url_username: root
        url_password: "{{ bmcpassword }}"
        validate_certs: false
      register: system

    - delegate_to: localhost
      ignore_errors: true
      uri:
        url: "{{ redfish_base_url }}{{ action }}"
        method: POST
        body_format: json
        body:
          ResetType: "{{ reset_type }}"
        url_username: root
        url_password: "{{ bmcpassword }}"
        validate_certs: false
        status_code:
          - 200
          - 204
      register: power
      vars:
        action: "{{ system.json.Actions['#ComputerSystem.Reset'].target }}"

    - when: power is failed
      block:
        - debug:
            msg: "{{ power.json }}"

        - fail:
