- hosts: systems
  gather_facts: false
  collections:
    - community.general
  vars:
    redfish_base_url: "https://{{ bmcAddr }}"
  tasks:
    - delegate_to: localhost
      uri:
        url: "{{ redfish_base_url }}/redfish/v1/Systems/System.Embedded.1"
        url_username: root
        url_password: "{{ bmcpassword }}"
        validate_certs: false
      register: system

    - debug:
        msg: "Power state: {{ system.json.PowerState }}"
